export const FETCH_ALL_TODOS = "fetchAllTodos";
export const ADD_TODO_SUCCESS = "addTodoSuccess";
export const ADD_TODO_ERROR = "addTodoError"
export const DELETE_TODO ="deleteTodo";
export const SELECT_TODO = "selectTodo";
export const DROP_SELECTED_TODO = "drop";
export const UPDATE_TODO_SUCCESS = "success";
export const UPDATE_TODO_ERROR = "error"
export const SWITCH_TYPE = "switchType";